# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your Blog Title
description: '' # write a nice description for your blog
baseurl: ''
remote_theme: adueck/cayman-blog
url: https://hyeonjinchoi.github.io/
# google_analytics: 'UA-XXXXXX-X'
twitter_username: 'twitter_username'

# Build settings
markdown: kramdown

permalink: '/:title/'

gems: [jekyll-paginate]

paginate: 10
